id: I2342D649
initial_creation_type: ebook
source_metadata:
  id: MIN-LC-017
  title: ༄༅། །དཔལ་གསང་བའི་སྙིང་པོ་དེ་ཁོ་ན་ཉིད་ངེས་པའི་རྒྱུད་ཀྱི་རྒྱལ་པོ་སྒྱུ་འཕྲུལ་དྲྭ་བ་སྤྱི་དོན་གྱི་སྒོ་ནས་གཏན་ལ་འབེབས་པར་བྱེད་པའི་ལེགས་བཤད་གསང་བདག་ཞལ་ལུང་ཞེས་བྱ་བའི་སྨད་ཆ་བཞུགས་སོ།
    །
  author: མཛད་པ་པོ། ལོ་ཆེན་དྷརྨ་ཤྲཱི། ངག་དབང་ཆོས་དཔལ་རྒྱ་མཚོ།
  authors: &id001
  - མཛད་པ་པོ། ལོ་ཆེན་དྷརྨ་ཤྲཱི། ངག་དབང་ཆོས་དཔལ་རྒྱ་མཚོ།
  sku: MIN-LC-017
  cover: MIN-LC-017.jpg
  volume: {}
ebook_metadata:
  title: ༄༅། །དཔལ་གསང་བའི་སྙིང་པོ་དེ་ཁོ་ན་ཉིད་ངེས་པའི་རྒྱུད་ཀྱི་རྒྱལ་པོ་སྒྱུ་འཕྲུལ་དྲྭ་བ་སྤྱི་དོན་གྱི་སྒོ་ནས་གཏན་ལ་འབེབས་པར་བྱེད་པའི་ལེགས་བཤད་གསང་བདག་ཞལ་ལུང་ཞེས་བྱ་བའི་སྨད་ཆ་བཞུགས་སོ།
    །
  authors: *id001
  sku: MIN-LC-017
  cover: MIN-LC-017.jpg
layers:
- Author
- BookTitle
- Chapter
- Commentary
- Sabche
- Yigchung
